EstructuraProgramacion 2/Controllers/Taller9Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EstructuraProgramacion_2.Models;

namespace EstructuraProgramacion_2.Controllers
{
    public class Taller9Controller : Controller
    {
        // GET: Taller7
        public ActionResult Index(int? nivel, double? a, double? b, double? c, double? d)
        {
            if (nivel != null)
            {
                ViewBag.nivel = nivel.Value;
                if (a != null)
                    ViewBag.a = a.Value;
                ViewBag.b = b.Value;
                ViewBag.c = c.Value;
                ViewBag.d = d.Value;
            }

            return View();
        }

        public ActionResult asp(int? nivel, double? a, double? b, double? c, double? d)
        {
            if (nivel != null)
            {
                string resultado = string.Empty;
                int n;
                n = nivel.Value;
                b *= 2;
                c *= 1;
                d *= 0; /*este si no 
            /sirve para nada*/

                // Nivel 3 ->
                if (a != null && n == 3)
                {
                    a *= 3;
                    resultado += a + "x^2+";
                }

                resultado += b + "x+" + c;
                ViewBag.Resultado = resultado;
            }

            return View();
        }
    }
}

EstructuraProgramacion 2/Views/Taller9/Index.cshtml
@using EstructuraProgramacion_2.Helpers
@using (Html.BeginForm("Index", "Taller9", FormMethod.Get, new { @Class = "row" }))
{
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="input-field col s6">
            <select name="nivel">
                <option value="" disabled selected>Seleccionar nivel</option>
                <option value="3">3</option>
                <option value="2">2</option>
            </select>
            <label>Nivel</label>
        </div>

        <div class="input-field col s6 a">
            <label for="a">AX^3</label>
            <input type="number" name="a" value="@ViewBag.a" />
        </div>

        <div class="input-field col s6">
            <label for="b">BX^2</label>
            <input type="number" name="b" value="@ViewBag.b" required />
        </div>

        <div class="input-field col s6">
            <label for="c">CX</label>
            <input type="number" name="c" value="@ViewBag.c" required />
        </div>

        <div class="input-field col s6">
            <label for="d">D</label>
            <input type="number" name="d" value="@ViewBag.d" required />
        </div>

        <div class="col-md-offset-2 col s12">
            <button type="submit" class="btn-floating btn-large waves-effect waves-light ">
                <i class="material-icons">done</i>
            </button>
        </div>

        @if (ViewBag.nivel != null)
        {
            string parametrosUrl = "?nivel=" + ViewBag.nivel + "&a=" + ViewBag.a + "&b=" + ViewBag.b + "&c=" + ViewBag.c + "&d=" + ViewBag.d;

            <div class="row">

                <div class="col s4">
                    PHP:
                    <iframe class="col s12" src="@Html.Raw("http://universidad.desarrollosahora.com/others/Ecuacion.php"+parametrosUrl)"></iframe>
                </div>

                <div class="col s4">
                    ASP MVC .NET C#:
                    <iframe class="col s12" src="@Html.Raw("/Taller9/asp"+parametrosUrl)"></iframe>
                </div>

                <div class="col s4">
                    JSP:
                    <iframe class="col s12" src="@Html.Raw("http://localhost:8080/Ecuacion.jsp"+parametrosUrl)"></iframe>
                </div>

            </div>
        }
    </div>



}
<br /><hr /><br/>
@using (Html.BeginForm("Index","Taller9",FormMethod.Get))
{
    <div class="row col s12 m3">
        <h6><b>Etiqueta Personalizada</b></h6>

        <div class="input-field col s6">
            <label  for="Start">Start</label>
            <input min="1" type="number" name="Start" required />
        </div>

        <div class="input-field col s6">
            <label for="End">End</label>
            <input min="2" type="number" name="End" required />
        </div>

        <div class="col-md-offset-2 col s12">
            <button type="submit" class="btn-floating btn-large waves-effect waves-light ">
                <i class="material-icons">done</i>
            </button>
        </div>
        @if (!string.IsNullOrWhiteSpace(Request.QueryString["Start"]))
        {
            @Html.Raw(ListaPrimosHelper
                .ListaPrimos(int.Parse(Request.QueryString["Start"]),
                            int.Parse(Request.QueryString["End"])
                            ));
        }

    </div>
}


<script>
    $(document).ready(function () {
        $('select').material_select();
        CambioNivel();
        function CambioNivel() {
            if ($('select').find('option:selected').val() == 3) {
                $(".a").show();
            } else {
                $(".a").hide();
            }
        }

        $("select").change(function () {
            CambioNivel();
        });
    });
</script>

EstructuraProgramacion 2/Views/Taller9/asp.cshtml
@{
    Layout = null;
}

@if (ViewBag.Resultado != null)
{
    <span>Primera Derivada: <b>@ViewBag.Resultado</b></span>
}