EstructuraProgramacion 2/Controllers/Taller8Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EstructuraProgramacion_2.Models;

namespace EstructuraProgramacion_2.Controllers
{
    public class Taller8Controller : Controller
    {
        // GET: Taller7
        public ActionResult Index(double? radio)
        {
            if (radio != null) { 
                ViewBag.radio = radio;
            }

            return View();
        }

        public ActionResult asp(double? radio)
        {
            if (radio != null)
            {
                double volumen = (4 * 3.14159265359 * Math.Pow(radio.Value, 3))/3;
                ViewBag.Volumen = volumen;
            }

            return View();
        }
    }
}

EstructuraProgramacion 2/Views/Taller8/Index.cshtml
@using (Html.BeginForm("Index", "Taller8", FormMethod.Post, new { @Class = "row" }))
{
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="input-field col s6">
            <label for="radio">Radio</label>
            <input type="number"name="radio" />
        </div>

        <div class="col-md-offset-2 col s12">
            <button type="submit" class="btn-floating btn-large waves-effect waves-light ">
                <i class="material-icons">done</i>
            </button>
        </div>

        @if (ViewBag.radio != null) { 
            <div class="row">
                
                <div class="col s4">
                    PHP:
                    <iframe class="col s12"src="http://universidad.desarrollosahora.com/others/php.php?radio=@ViewBag.radio"></iframe>
                </div>

                <div class="col s4">
                    ASP MVC .NET C#:
                    <iframe class="col s12" src="/Taller8/asp?radio=@ViewBag.radio"></iframe>
                </div>

                <div class="col s4">
                    JSP:
                    <iframe class="col s12" src="http://localhost:8080/Esfera.jsp?radio=@ViewBag.radio"></iframe>
                </div>

            </div>
        }
    </div>

}

EstructuraProgramacion 2/Views/Taller8/asp.cshtml
@{
    Layout = null;
}

        @if (ViewBag.Volumen != null) { 
            <span>Volumen: <b>@ViewBag.Volumen</b></span>
        }